---
ansible_connection: httpapi
ansible_network_os: eos
# update usename and passsword in inventory.yml
# ansible_user: arista
# ansible_password: aristaedf8
ansible_become: yes
ansible_become_method: enable
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
ansible_python_interpreter: $(which python3)
