---
- name: Update Configlets
  hosts: host1
  gather_facts: no

# https://ansible-arista-howto.readthedocs.io/en/latest/EOS_CONFIG.html#configure-arista-eos-with-ansible

  tasks:

    - name: Add Access-List to Switches
      eos_config:
        lines:
        - 10 permit ip host 192.0.2.1 any log
        - 20 permit ip host 192.0.2.2 any log
        - 30 permit ip host 192.0.2.3 any log
        - 40 permit ip host 192.0.2.4 any log
        parents: ip access-list test
        before: no ip access-list test
        replace: block

    - name: Add VLANs to Switches by Jinja Template with Dictionary
      eos_config:
        src: "templates/vlan-template-config.j2"

