---
- name: Update Configlets
  hosts: cvp
  connection: local
  gather_facts: no

  collections:
    - arista.cvp
    - arista.avd

# Device Inventory dictionary is stored in host_vars/cvp/devices_inventory.yml

  tasks:


    # Upload configlets from a directory
    - name: "Upload configlets to CVP {{ inventory_hostname }}"
      tags: [ upload, full ]
      import_role:
          name: arista.avd.cvp_configlet_upload
      vars:
        configlet_directory: 'cvp_configlets'
        file_extension: 'txt'
        configlets_cvp_prefix: 'ATDDEMO'

    # Task will build/update Container Topology and Attach configlets to the Containers
    - name: "Updating Containers & Attaching Configlets"
      tags: [ update, full ]
      cv_container_v3:
        topology: "{{ CVP_CONTAINERS }}"
      register: CVP_CONTAINERS_RESULT

    # Task will update Device configlet list and which container the device is connected
    - name: "Updating Configlets on Devices"
      tags: [ update, full ]
      cv_device_v3:
        devices: "{{ CVP_DEVICES }}"
        state: present
      register: CVP_DEVICES_RESULT

    # Reminder message just in case there are Tasks that need to be executed in CVP
    # We do not automatically execute any tasks in CVP
    - name: "Follow Up Message"
      tags: [ always ]
      debug:
        msg: "If needed, manually create change control & execute any pending tasks in CVP to apply changes"



